export const actionType = {
    GET_HOME:"GET_HOME",
    GET_PRODUCT:"GET_PRODUCT",
    GET_PRODUCT_BY_CATEGORY:"GET_PRODUCT_BY_CATEGORY",
    USER_DETALIS:"USER_DETALIS",
    USER_DETALIS_CLEAR:"USER_DETALIS_CLEAR",
    GET_PRODUCT_BY_CATEGORY_ID:"GET_PRODUCT_BY_CATEGORY_ID",
    GET_PRODUCT_BY_SEARCH:"GET_PRODUCT_BY_SEARCH",
    GET_SITE_DETAILS:"GET_SITE_DETAILS"
}